version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: auth-manager-local-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user123
      - MONGO_INITDB_ROOT_PASSWORD=senha123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
